apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: catalogo
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      # ── Posicionamento: VM2 (camada de aplicação) ──
      nodeSelector:
        layer: app
      containers:
        - name: fastapi
          image: SEU_DOCKERHUB_USER/catalogo-backend:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "postgres-service.catalogo.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: LOKI_URL
              value: "http://loki-service.catalogo.svc.cluster.local:3100"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
